### ISSUE TITLE
Adding a resource fails but does not break the pipeline

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [keptn-sandbox/keptn-azure-devops-extension#46]
Using 1.4.0 I ran into the following issue while trying to add a file:

```
metadata endpoint exists...
keptnVersion = 0.10.0
adding resource /home/vsts/work/1/s/.keptn/helm/foobar.tgz to keptn target helm/foobar.tgz
{ Error: Request failed with status code 400
    at createError (/home/vsts/work/_tasks/AddKeptnResourceTask_f423c3f9-bd6d-11ea-b3de-0242ac130004/1.1.0/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/vsts/work/_tasks/AddKeptnResourceTask_f423c3f9-bd6d-11ea-b3de-0242ac130004/1.1.0/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/home/vsts/work/_tasks/AddKeptnResourceTask_f423c3f9-bd6d-11ea-b3de-0242ac130004/1.1.0/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
...
     data: { code: 400, message: 'Could not unarchive Helm chart' } },
```
![image](https://user-images.githubusercontent.com/56065213/141462516-478eaa92-ed0b-4186-83f2-151ab7f977bf.png)

This is not good, because as a user, you are under the impression that everything worked, although it didn't.

# Definition of Done

- [ ] Add Resource task fails if the corresponding API call fails
- [ ] The response error message is shown instead of a stacktrace
 

However, the pipeline continued.

**Comment by Raffy23** [comment]
The problem with the task not failing seems to have already been fixed in the master branch. 
With #93 the error message should be more readable. `Could not unarchive Helm chart` is displayed as message instead of the generic `Request failed with status code 400` message.
